[project]
name = "futureguidedlearning-main"
version = "0.1.0"
description = "Future Guided Learning for Time Series Prediction (Epilepsy Seizure Detection)"
requires-python = ">=3.11, <3.12"
dependencies = [
    "scipy==1.11.3",
    "numpy==1.26.2",
    "torch==2.1.1",
    "tqdm==4.66.1",
    "matplotlib==3.8.1",
    "datetime==5.4",
    "argparse==1.4.0",
    "jitcdde",
    "jitcxde_common",
    "sympy",
    "cantera>=3.2.0",
]


